@host = http://localhost:5000/api/v1/products


###
GET {{host}}/static HTTP/1.1
content-type: application/json

{

}

###
GET {{host}}?name=aa HTTP/1.1
content-type: application/json

{
    
}


###
GET {{host}}?page=3 HTTP/1.1
content-type: application/json

{
    
}